### ISSUE TITLE
Dont work anymore

### ISSUE THREAD

**Issue by PlayBoy31** [essembeh/kimsufi-checker#3]
Hello, the script dosent more anymore

The structure has changed maybe

**Comment by essembeh** [comment]
Hello/Salut

Je viens de retester (car je ne l'utilise pas en ce moment), et je n'ai pas de problème.
Tu peux me donner plus de détails sur ton erreur?

**Comment by PlayBoy31** [comment]
Je teste par exemple avec kimsufi-checker -s 5 --zone bhs 1804sk23
...

le 1804sk23 est bien dispo sur le site kimsufi mais le script affiche seulement: "." pour chaque vérification. le premier point est bleu, les suivant sont vert, il n'y a pas de trace qui s'affiche cf. =>```
  **print(
                            Style.GREEN.apply(
                                "\n[{date}] Plan {plan} is available".format(
                                    date=now(), plan=plan
                                )
                            ),
                            flush=True,
                        )**
```

**Comment by essembeh** [comment]
C'est normal, les actions sont déclenchées lors d'un *changement* d'état.
Le premier point est bleu car il n'y a pas d'état précédent. Les autres points sont verts pour indiquer que le plan est dispo.

Je vais profiter de migrer le projet sous poetry pour mieux gérer les log (verbose/quiet).

**Comment by PlayBoy31** [comment]
Non, par exemple le 1804sk22 sur BHS nest pas dispo et le script sort des points vert !

**Comment by essembeh** [comment]
Pardon, j'ai répondu trop vite et je me rend compte que je devrais documenter les couleurs:
* point bleu: initialisation de l'état
* point vert: le plan est dans le même état que précedemment
Si le plan *devient* dispo ou *n'est plus* dispo, alors il y a un message clair et le déclenchement des actions si donnée avec les arguments `-x` et `-X`

J'espère avoir répondu à tes questions.
Je me note de mieux documenter le comportement.

**Comment by PlayBoy31** [comment]
Ok je comprends mieux merci

Cela pourrait être bien d’avoir un petit print sur l'état initial dispo/pas dispo, un print textuel ...

Par exemple, si jamais je mets le script dans un CRON (ce qui est mon cas) sur un serveur, et que mon serveur je l'ai rebooté et que en fait un serveur KS était disponible, je ne recevrai jamais la notification !

C'est pour cela qu'il faut tester l’état initial et afficher aussi un trace console

**Comment by essembeh** [comment]
Je viens de push une nouvelle version avec plus de message sur l'état initial.
Aussi, on peut déclencher les actions `-x` et `-X` au lancement suivant l'état des plans, avec `--execute-on-init`.

**Comment by PlayBoy31** [comment]
Hello, je viens de test, c'est pas mal. Merci pour les évolutions !
